version: '3.5'
services:
  api:
    image: apirestful_flask:v1
    build: ./apirestful_flask
    entrypoint: "/bin/sh -c"
    command: "exit 0"
  database-books:
    image: postgres:13-alpine
    env_file: db-books/database.conf
    volumes:
      - db_volume-books:/var/lib/postgresql/data
  database-readers:
    image: postgres:13-alpine
    env_file: db-readers/database.conf
    volumes:
      - db_volume-readers:/var/lib/postgresql/data
  api-books:
    image: apirestful_flask:v1
    env_file: ./books/src/app/database.conf
    ports:
      - 5000:5000
    volumes:
      - ./books/src/app:/usr/src/app/ 
    depends_on:
      - api
      - database-books
  api-readers:
    image: apirestful_flask:v1
    env_file: ./readers/src/app/database.conf
    ports:
      - 5001:5000
    volumes:
      - ./readers/src/app:/usr/src/app/
    depends_on:
      - api
      - database-readers
  web:
    image: php:7.4.12-apache-buster
    volumes:
      - ./web:/var/www/html 
    ports:
      - 80:80 
    depends_on:
      - api-readers
      - api-books

volumes:
  db_volume-books:
  db_volume-readers:
